### ISSUE TITLE
Sympy support

### ISSUE THREAD

**Issue by i2000s** [pychebfun/pychebfun#1]
Dear developers,

I have not tried the python version of Chebfun yet, but I would like to ask if pychebfun has a sympy interface? Maybe the sympy can make Chebfun a really symbolic calculator for advanced usages!

I am sorry if this post bothers you.

Bests,
Qi

**Comment by olivierverdier** [comment]
Hi, sorry for answering so late: no, there is no interface to sympy. The approach is quite different, as we do not manipulate symbold, but accurate interpolations.

Feel fre to contact me if you have other questions.
