### ISSUE TITLE
alternate license?

### ISSUE THREAD

**Issue by jason-s** [pychebfun/pychebfun#4]
Have you considered using an alternate license rather than GPLv2? (such as LGPL or one of the other less-restrictive licenses like Apache, MIT, BSD, etc.)

The Chebfun library for MATLAB is BSD-licensed (see https://github.com/chebfun/chebfun/blob/development/LICENSE.txt) and I'm looking for a Python equivalent but I need to use it in a commercial environment as a rather small piece of a much larger system.

Alternatively submit something that can be made part of scipy. (with its license.)

**Comment by olivierverdier** [comment]
I'm all for changing the licence. @cswiercz , what do you think?

**Comment by cswiercz** [comment]
I'm honored to be included! The license change is fine by me. I'll leave the choice to your discretion. Any of the MIT or BSD style licenses are fine.

**Comment by olivierverdier** [comment]
@cswiercz  thanks! The license is now BSD (155817711981ea4ca3313e19713a4a8589058baf)
