### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by ibell** [pychebfun/pychebfun#5]
I'm a bit confused about the licensing of pychebfun.  On the README, it says "This work is licensed under the GNU General Public License v2.", but it seems the LICENSE file says BSD 3-clause.  Perhaps this should be harmonized/fixed?

I very much appreciate the work that you all have done on pychebfun; it was really helpful (especially your Jupyter notebook) in the development of ChebTools (https://github.com/usnistgov/ChebTools), a C++11<->python analog of ``chebfun``.  The reason I want to be sure about the licensing is so that I can use your code for numpy ufunc overloading in ChebTools.

**Comment by olivierverdier** [comment]
Yes you can, sorry I have missed this.
